services:
  dev-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com.br"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2022!"
    ports:
      - "16543:80"
    depends_on:
      - dev-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge